In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [4]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
## preprocessing the data
## Drop irrelevent columns
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# Encoding categorical variables
label_encode_gender = LabelEncoder()
data["Gender"] = label_encode_gender.fit_transform(data["Gender"])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
# One Hot Encoding Geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder(sparse_output = False, drop = 'first')
geo_encoder = onehot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoder

array([[0., 0.],
       [0., 1.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 0.],
       [0., 0.]])

In [8]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_Germany', 'Geography_Spain'], dtype=object)

In [9]:
geo_encoded_df = pd.DataFrame(geo_encoder, columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_Germany  Geography_Spain
0                   0.0              0.0
1                   0.0              1.0
2                   0.0              0.0
3                   0.0              0.0
4                   0.0              1.0
...                 ...              ...
9995                0.0              0.0
9996                0.0              0.0
9997                0.0              0.0
9998                1.0              0.0
9999                0.0              0.0

[10000 rows x 2 columns]

In [10]:
# Combining one hot encoder column with the original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df],axis = 1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0

In [11]:
# save to encoder pickle file

with open("label_encode_gender.pkl", 'wb') as file:
    pickle.dump(label_encode_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [12]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0

In [13]:
# Divide the dataset into independent and dependent features
X = data.drop('Exited', axis=1)
y = data['Exited']

# split the data into training and testing ses
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state = 42)

## Scale thses features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.36766974,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ...,  1.6612541 ,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.25280688,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ..., -0.1427649 ,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ..., -0.05082558,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.81456811,
         1.72572313, -0.57638802]])

In [15]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [16]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,0.0,0.0

## ANN Implementation

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [18]:
X_train.shape[1]

11

In [20]:
## Build Our ANN model

model = Sequential([
    Dense(64, activation='relu', input_shape =(X_train.shape[1],)),# Hidden layer 1 connected to input layer with 63 neurons
    Dense(32, activation='relu'), #Hidden layer 2 with 32 neurons
    Dense(1, activation='sigmoid') # Output layer

])

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                768

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2881 (11.25 KB)
Trainable params: 2881 (11.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [22]:
# Optimiser and loss
import tensorflow as tf
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
loss = tf.keras.losses.BinaryCrossentropy()
loss

In [23]:
# Compile the model
model.compile(optimizer=opt, loss=loss, metrics=['accuracy'])

In [24]:
model

In [25]:
## Setup the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "log/fit/" +datetime.datetime.now().strftime("%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [26]:
## Setup Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [27]:
# Train the model

history = model.fit(
    X_train,y_train,validation_data=(X_train,y_train),epochs = 100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 16s 23ms/step - loss: 0.4661 - accuracy: 0.7906 - val_loss: 0.4053 - val_accuracy: 0.8292
Epoch 2/100
250/250 [==============================] - 4s 18ms/step - loss: 0.3824 - accuracy: 0.8435 - val_loss: 0.3587 - val_accuracy: 0.8547
Epoch 3/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3523 - accuracy: 0.8564 - val_loss: 0.3436 - val_accuracy: 0.8561
Epoch 4/100
250/250 [==============================] - 4s 14ms/step - loss: 0.3419 - accuracy: 0.8595 - val_loss: 0.3359 - val_accuracy: 0.8624
Epoch 5/100
250/250 [==============================] - 6s 24ms/step - loss: 0.3405 - accuracy: 0.8589 - val_loss: 0.3309 - val_accuracy: 0.8630
Epoch 6/100
250/250 [==============================] - 5s 18ms/step - loss: 0.3348 - accuracy: 0.8626 - val_loss: 0.3280 - val_accuracy: 0.8658
Epoch 7/100
250/250 [==============================] - 9s 35ms/step - loss: 0.3328 - accuracy: 0.8631 - val_loss: 0.3257 - val_accuracy: 0.8645
Epoch 8/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3307 - accuracy: 0.8635 - val_loss: 0.3237 - val_accuracy: 0.8655
Epoch 9/100
250/250 [==============================] - 3s 14ms/step - loss: 0.3294 - accuracy: 0.8624 - val_loss: 0.3195 - val_accuracy: 0.8679
Epoch 10/100
250/250 [==============================] - 7s 29ms/step - loss: 0.3260 - accuracy: 0.8651 - val_loss: 0.3190 - val_accuracy: 0.8681
Epoch 11/100
250/250 [==============================] - 4s 18ms/step - loss: 0.3242 - accuracy: 0.8658 - val_loss: 0.3185 - val_accuracy: 0.8704
Epoch 12/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3236 - accuracy: 0.8664 - val_loss: 0.3155 - val_accuracy: 0.8705
Epoch 13/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3200 - accuracy: 0.8670 - val_loss: 0.3171 - val_accuracy: 0.8691
Epoch 14/100
250/250 [==============================] - 7s 28ms/step - loss: 0.3199 - accuracy: 0.8677 - val_loss: 0.3152 - val_accuracy: 0.8706
Epoch 15/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3173 - accuracy: 0.8691 - val_loss: 0.3106 - val_accuracy: 0.8700
Epoch 16/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3149 - accuracy: 0.8698 - val_loss: 0.3117 - val_accuracy: 0.8692
Epoch 17/100
250/250 [==============================] - 8s 30ms/step - loss: 0.3158 - accuracy: 0.8679 - val_loss: 0.3081 - val_accuracy: 0.8723
Epoch 18/100
250/250 [==============================] - 8s 30ms/step - loss: 0.3140 - accuracy: 0.8695 - val_loss: 0.3099 - val_accuracy: 0.8705
Epoch 19/100
250/250 [==============================] - 8s 31ms/step - loss: 0.3122 - accuracy: 0.8706 - val_loss: 0.3091 - val_accuracy: 0.8702
Epoch 20/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3102 - accuracy: 0.8708 - val_loss: 0.3050 - val_accuracy: 0.8739
Epoch 21/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3095 - accuracy: 0.8725 - val_loss: 0.3019 - val_accuracy: 0.8751
Epoch 22/100
250/250 [==============================] - 8s 31ms/step - loss: 0.3085 - accuracy: 0.8695 - val_loss: 0.3002 - val_accuracy: 0.8756
Epoch 23/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3086 - accuracy: 0.8711 - val_loss: 0.3000 - val_accuracy: 0.8766
Epoch 24/100
250/250 [==============================] - 10s 42ms/step - loss: 0.3048 - accuracy: 0.8737 - val_loss: 0.2999 - val_accuracy: 0.8775
Epoch 25/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3063 - accuracy: 0.8712 - val_loss: 0.2957 - val_accuracy: 0.8777
Epoch 26/100
250/250 [==============================] - 3s 13ms/step - loss: 0.3021 - accuracy: 0.8746 - val_loss: 0.2956 - val_accuracy: 0.8781
Epoch 27/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3021 - accuracy: 0.8754 - val_loss: 0.2938 - val_accuracy: 0.8781
Epoch 28/100
250/250 [==============================] - 7s 27ms/step - loss: 0.3025 - accuracy: 0.8748 - val_loss: 0.2947 - val_accuracy: 0.8795
Epoch 29/100
250/250 [==============================] - 5s 21ms/step - loss: 0.3002 - accuracy: 0.8780 - val_loss: 0.2915 - val_accuracy: 0.8795
Epoch 30/100
250/250 [==============================] - 6s 25ms/step - loss: 0.2979 - accuracy: 0.8776 - val_loss: 0.2913 - val_accuracy: 0.8781
Epoch 31/100
250/250 [==============================] - 6s 25ms/step - loss: 0.2980 - accuracy: 0.8739 - val_loss: 0.2902 - val_accuracy: 0.8775
Epoch 32/100
250/250 [==============================] - 10s 40ms/step - loss: 0.2974 - accuracy: 0.8750 - val_loss: 0.2867 - val_accuracy: 0.8806
Epoch 33/100
250/250 [==============================] - 5s 21ms/step - loss: 0.2949 - accuracy: 0.8773 - val_loss: 0.2864 - val_accuracy: 0.8802
Epoch 34/100
250/250 [==============================] - 3s 11ms/step - loss: 0.2946 - accuracy: 0.8777 - val_loss: 0.2846 - val_accuracy: 0.8804
Epoch 35/100
250/250 [==============================] - 4s 14ms/step - loss: 0.2927 - accuracy: 0.8761 - val_loss: 0.2883 - val_accuracy: 0.8817
Epoch 36/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2923 - accuracy: 0.8785 - val_loss: 0.2838 - val_accuracy: 0.8839
Epoch 37/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2923 - accuracy: 0.8776 - val_loss: 0.2830 - val_accuracy: 0.8814
Epoch 38/100
250/250 [==============================] - 4s 14ms/step - loss: 0.2902 - accuracy: 0.8801 - val_loss: 0.2800 - val_accuracy: 0.8851
Epoch 39/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2888 - accuracy: 0.8799 - val_loss: 0.2787 - val_accuracy: 0.8834
Epoch 40/100
250/250 [==============================] - 6s 25ms/step - loss: 0.2881 - accuracy: 0.8786 - val_loss: 0.2822 - val_accuracy: 0.8823
Epoch 41/100
250/250 [==============================] - 5s 21ms/step - loss: 0.2875 - accuracy: 0.8821 - val_loss: 0.2779 - val_accuracy: 0.8857
Epoch 42/100
250/250 [==============================] - 3s 14ms/step - loss: 0.2857 - accuracy: 0.8798 - val_loss: 0.2793 - val_accuracy: 0.8826
Epoch 43/100
250/250 [==============================] - 3s 14ms/step - loss: 0.2843 - accuracy: 0.8835 - val_loss: 0.2737 - val_accuracy: 0.8870
Epoch 44/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2829 - accuracy: 0.8820 - val_loss: 0.2760 - val_accuracy: 0.8846
Epoch 45/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2829 - accuracy: 0.8824 - val_loss: 0.2729 - val_accuracy: 0.8889
Epoch 46/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2818 - accuracy: 0.8805 - val_loss: 0.2746 - val_accuracy: 0.8866
Epoch 47/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2813 - accuracy: 0.8825 - val_loss: 0.2737 - val_accuracy: 0.8871
Epoch 48/100
250/250 [==============================] - 6s 23ms/step - loss: 0.2803 - accuracy: 0.8819 - val_loss: 0.2691 - val_accuracy: 0.8879
Epoch 49/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2802 - accuracy: 0.8821 - val_loss: 0.2741 - val_accuracy: 0.8845
Epoch 50/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2801 - accuracy: 0.8844 - val_loss: 0.2700 - val_accuracy: 0.8873
Epoch 51/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2769 - accuracy: 0.8834 - val_loss: 0.2660 - val_accuracy: 0.8894
Epoch 52/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2764 - accuracy: 0.8831 - val_loss: 0.2680 - val_accuracy: 0.8875
Epoch 53/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2745 - accuracy: 0.8851 - val_loss: 0.2648 - val_accuracy: 0.8891
Epoch 54/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2741 - accuracy: 0.8841 - val_loss: 0.2679 - val_accuracy: 0.8875
Epoch 55/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2738 - accuracy: 0.8850 - val_loss: 0.2628 - val_accuracy: 0.8896
Epoch 56/100
250/250 [==============================] - 6s 23ms/step - loss: 0.2730 - accuracy: 0.8842 - val_loss: 0.2661 - val_accuracy: 0.8882
Epoch 57/100
250/250 [==============================] - 5s 20ms/step - loss: 0.2723 - accuracy: 0.8863 - val_loss: 0.2601 - val_accuracy: 0.8903
Epoch 58/100
250/250 [==============================] - 6s 23ms/step - loss: 0.2709 - accuracy: 0.8846 - val_loss: 0.2605 - val_accuracy: 0.8900
Epoch 59/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2697 - accuracy: 0.8888 - val_loss: 0.2597 - val_accuracy: 0.8909
Epoch 60/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2683 - accuracy: 0.8882 - val_loss: 0.2654 - val_accuracy: 0.8879
Epoch 61/100
250/250 [==============================] - 3s 13ms/step - loss: 0.2691 - accuracy: 0.8856 - val_loss: 0.2638 - val_accuracy: 0.8863
Epoch 62/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2661 - accuracy: 0.8870 - val_loss: 0.2573 - val_accuracy: 0.8911
Epoch 63/100
250/250 [==============================] - 4s 14ms/step - loss: 0.2683 - accuracy: 0.8849 - val_loss: 0.2565 - val_accuracy: 0.8939
Epoch 64/100
250/250 [==============================] - 7s 27ms/step - loss: 0.2666 - accuracy: 0.8867 - val_loss: 0.2580 - val_accuracy: 0.8919
Epoch 65/100
250/250 [==============================] - 6s 22ms/step - loss: 0.2673 - accuracy: 0.8839 - val_loss: 0.2587 - val_accuracy: 0.8916
Epoch 66/100
250/250 [==============================] - 4s 18ms/step - loss: 0.2643 - accuracy: 0.8895 - val_loss: 0.2626 - val_accuracy: 0.8914
Epoch 67/100
250/250 [==============================] - 7s 26ms/step - loss: 0.2653 - accuracy: 0.8856 - val_loss: 0.2556 - val_accuracy: 0.8930
Epoch 68/100
250/250 [==============================] - 5s 20ms/step - loss: 0.2622 - accuracy: 0.8878 - val_loss: 0.2552 - val_accuracy: 0.8936
Epoch 69/100
250/250 [==============================] - 8s 33ms/step - loss: 0.2625 - accuracy: 0.8899 - val_loss: 0.2546 - val_accuracy: 0.8940
Epoch 70/100
250/250 [==============================] - 5s 21ms/step - loss: 0.2625 - accuracy: 0.8884 - val_loss: 0.2511 - val_accuracy: 0.8964
Epoch 71/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2615 - accuracy: 0.8901 - val_loss: 0.2499 - val_accuracy: 0.8957
Epoch 72/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2587 - accuracy: 0.8913 - val_loss: 0.2480 - val_accuracy: 0.8957
Epoch 73/100
250/250 [==============================] - 4s 14ms/step - loss: 0.2611 - accuracy: 0.8903 - val_loss: 0.2474 - val_accuracy: 0.8951
Epoch 74/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2576 - accuracy: 0.8896 - val_loss: 0.2493 - val_accuracy: 0.8984
Epoch 75/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2571 - accuracy: 0.8921 - val_loss: 0.2465 - val_accuracy: 0.8947
Epoch 76/100
250/250 [==============================] - 6s 23ms/step - loss: 0.2571 - accuracy: 0.8919 - val_loss: 0.2450 - val_accuracy: 0.8984
Epoch 77/100
250/250 [==============================] - 4s 14ms/step - loss: 0.2557 - accuracy: 0.8920 - val_loss: 0.2490 - val_accuracy: 0.8931
Epoch 78/100
250/250 [==============================] - 4s 16ms/step - loss: 0.2567 - accuracy: 0.8913 - val_loss: 0.2436 - val_accuracy: 0.8964
Epoch 79/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2552 - accuracy: 0.8895 - val_loss: 0.2434 - val_accuracy: 0.8966
Epoch 80/100
250/250 [==============================] - 3s 14ms/step - loss: 0.2516 - accuracy: 0.8932 - val_loss: 0.2440 - val_accuracy: 0.8965
Epoch 81/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2516 - accuracy: 0.8964 - val_loss: 0.2417 - val_accuracy: 0.8976
Epoch 82/100
250/250 [==============================] - 3s 12ms/step - loss: 0.2536 - accuracy: 0.8929 - val_loss: 0.2411 - val_accuracy: 0.8974
Epoch 83/100
250/250 [==============================] - 4s 18ms/step - loss: 0.2533 - accuracy: 0.8920 - val_loss: 0.2454 - val_accuracy: 0.8960
Epoch 84/100
250/250 [==============================] - 17s 66ms/step - loss: 0.2521 - accuracy: 0.8919 - val_loss: 0.2385 - val_accuracy: 0.8996
Epoch 85/100
250/250 [==============================] - 20s 82ms/step - loss: 0.2508 - accuracy: 0.8920 - val_loss: 0.2373 - val_accuracy: 0.9007
Epoch 86/100
250/250 [==============================] - 14s 57ms/step - loss: 0.2501 - accuracy: 0.8921 - val_loss: 0.2388 - val_accuracy: 0.8981
Epoch 87/100
250/250 [==============================] - 9s 34ms/step - loss: 0.2479 - accuracy: 0.8935 - val_loss: 0.2505 - val_accuracy: 0.8910
Epoch 88/100
250/250 [==============================] - 5s 21ms/step - loss: 0.2471 - accuracy: 0.8950 - val_loss: 0.2415 - val_accuracy: 0.8972
Epoch 89/100
250/250 [==============================] - 10s 39ms/step - loss: 0.2469 - accuracy: 0.8964 - val_loss: 0.2381 - val_accuracy: 0.8995
Epoch 90/100
250/250 [==============================] - 9s 35ms/step - loss: 0.2469 - accuracy: 0.8950 - val_loss: 0.2435 - val_accuracy: 0.8978
Epoch 91/100
250/250 [==============================] - 4s 18ms/step - loss: 0.2463 - accuracy: 0.8936 - val_loss: 0.2509 - val_accuracy: 0.8910
Epoch 92/100
250/250 [==============================] - 4s 16ms/step - loss: 0.2460 - accuracy: 0.8967 - val_loss: 0.2333 - val_accuracy: 0.9026
Epoch 93/100
250/250 [==============================] - 5s 21ms/step - loss: 0.2436 - accuracy: 0.8994 - val_loss: 0.2327 - val_accuracy: 0.9029
Epoch 94/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2447 - accuracy: 0.8956 - val_loss: 0.2308 - val_accuracy: 0.9034
Epoch 95/100
250/250 [==============================] - 4s 14ms/step - loss: 0.2431 - accuracy: 0.8972 - val_loss: 0.2313 - val_accuracy: 0.9059
Epoch 96/100
250/250 [==============================] - 5s 18ms/step - loss: 0.2434 - accuracy: 0.8964 - val_loss: 0.2296 - val_accuracy: 0.9038
Epoch 97/100
250/250 [==============================] - 8s 31ms/step - loss: 0.2428 - accuracy: 0.8978 - val_loss: 0.2263 - val_accuracy: 0.9062
Epoch 98/100
250/250 [==============================] - 5s 20ms/step - loss: 0.2404 - accuracy: 0.8995 - val_loss: 0.2304 - val_accuracy: 0.9032
Epoch 99/100
250/250 [==============================] - 9s 34ms/step - loss: 0.2396 - accuracy: 0.9000 - val_loss: 0.2295 - val_accuracy: 0.9047
Epoch 100/100
250/250 [==============================] - 4s 15ms/step - loss: 0.2397 - accuracy: 0.8979 - val_loss: 0.2249 - val_accuracy: 0.9087

In [28]:
model.save("model.h5")

h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [29]:
## Load Tensorboard Extension
%load_ext tensorboard

In [34]:
%tensorboard --logdir log/fit

Reusing TensorBoard on port 6006 (pid 33212), started 0:00:18 ago. (Use '!kill 33212' to kill it.)