In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

WARNING:tensorflow:From h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [4]:
## Load the trained model,scaler pickle, onehot encode pickle
model = load_model('model.h5')

## Load the encoder and scaler
with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)

with open('label_encode_gender.pkl', 'rb') as file:
    label_encode_gender = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:From h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [5]:
# Example input data

input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [17]:
# one hot encod 'Geography'

geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded, columns = onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_Germany  Geography_Spain
0                0.0              0.0

In [12]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_Germany', 'Geography_Spain'], dtype=object)

In [19]:
input_df = pd.DataFrame(input_data, index=[0])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [20]:
# Encode categorical variable Gender

input_df['Gender'] = label_encode_gender.transform(input_df[['Gender']])
input_df

h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [21]:
# Concatenate the one hot encoded Geography with the input dataframe
input_df = pd.concat([input_df.drop('Geography', axis = 1), geo_encoded_df], axis = 1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,0.0,0.0

In [22]:
# Scaling the input data

input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221, -0.57946723,
        -0.57638802]])

In [24]:
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 124ms/step

array([[0.10054901]], dtype=float32)

In [28]:
prediction_proba = prediction[0][0]

In [29]:
prediction_proba

0.10054901

In [30]:
if prediction_proba > 0.5:
    print("The customer is likely to churn")
else:
    print(("The customer is not likely to churn"))

The customer is not likely to churn

In [32]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## Predicting for new data

In [42]:
new_input_data = {
    'CreditScore': 619,
    'Geography': 'France',
    'Gender': 'Female',
    'Age': 42,
    'Tenure': 2,
    'Balance': 0.00,
    'NumOfProducts': 1,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 101348
}

In [46]:
# one hot encod 'Geography'

new_geo_encoded = onehot_encoder_geo.transform([[new_input_data['Geography']]])
new_geo_encoded_df = pd.DataFrame(geo_encoded, columns = onehot_encoder_geo.get_feature_names_out(["Geography"]))
new_geo_encoded_df

h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_Germany  Geography_Spain
0                0.0              0.0

In [44]:
new_input_df = pd.DataFrame(new_input_data, index=[0])
new_input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.0,1,1,1,101348

In [45]:
# Encode categorical variable Gender

new_input_df['Gender'] = label_encode_gender.transform(new_input_df[['Gender']])
new_input_df

h:\Volume H\GEN AI_Langchain_Krish\Deep_Learning _for_NLP\ANN_Project_IMplementation\ANN_Project_End_to_End\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,0,42,2,0.0,1,1,1,101348

In [47]:
# Concatenate the one hot encoded Geography with the input dataframe
new_input_df = pd.concat([new_input_df.drop('Geography', axis = 1), new_geo_encoded_df], axis = 1)
new_input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain
0,619,0,42,2,0.0,1,1,1,101348,0.0,0.0

In [48]:
# Scaling the input data

new_input_scaled = scaler.transform(new_input_df)
new_input_scaled

array([[-0.33880827, -1.09499335,  0.29493847, -1.04241787, -1.21847056,
        -0.91668767,  0.64920267,  0.97481699,  0.01593854, -0.57946723,
        -0.57638802]])

In [49]:
new_prediction = model.predict(new_input_scaled)
new_prediction

1/1 [==============================] - 3s 3s/step

array([[0.13199641]], dtype=float32)

In [54]:
new_prediction_proba = new_prediction[0][0]
new_prediction_proba

0.13199641

In [55]:
if new_prediction_proba > 0.5:
    print('The customer is likely to churn')
else:
    print('The customer is not likely to churn')

The customer is not likely to churn